### PR TITLE
Add write data to csv file in current path.

### PR DESCRIPTION
**Pull request by iosiuk**

### CODE REVIEW

**Comment by MarkEdmondson1234** [comment]
I had something like this in an earlier version but then I realized you can pipe the results into a csv file if needed. Does that not suit your use case? It seemed more flexible to let users decide name of file etc.


________________________________

**Comment by iosiuk** [comment]
How to do this in the current package version?

**Comment by MarkEdmondson1234** [comment]
For the CLI you pipe it as documented here https://github.com/MarkEdmondson1234/gago/blob/master/gagocli/README.md

It uses a gago.WriteCSV method that can write to a file or stdout etc.


________________________________

**Comment by MarkEdmondson1234** [comment]
WriteCSV can take any stream output func

WriteCSV(report *ParseReport, file *os.File)

https://github.com/MarkEdmondson1234/gago/blob/834e269ddde25c23111db402198b43e60e4b864b/gago/reports.go#L200


________________________________

**Comment by MarkEdmondson1234** [comment]
So I think I can close this?  As its already in, just perhaps could do with better docs.

**Pull request closed without merging**
